### ISSUE TITLE
Change Q3 wording

### ISSUE THREAD

**Issue by GA-MEB** [ga-wdi-boston/html-css-overview-assessment#23]
> "Any elements that belong both to the `important` and `red` classes"

should be 

> "Only those elements belonging to both the `important` and `red` classes"

**Comment by GA-MEB** [comment]
Also 

> "Any `p` elements whose parent elements are `div`s"

should be

>  "All `p` elements whose parent elements are `div`s"

**Comment by laurenfazah** [comment]
@MattB-GA-Boston fixed!
