### ISSUE TITLE
Questions are not in line with lesson objectives

### ISSUE THREAD

**Issue by raq929** [ga-wdi-boston/html-css-overview-assessment#91]
Question 1 is not covered in either https://github.com/ga-wdi-boston/html-css or https://github.com/ga-wdi-boston/html-css-layout.
I think we should remove this question from the diagnostic. 

Question 5 - Understanding the box model is not an explicit objective in https://github.com/ga-wdi-boston/html-css-layout, which introduces the concept. I propose keeping this question and changing the objectives on that repo accordingly. 

@gaand, do you have thoughts on this? (Other people's thoughts are also welcome.)

**Comment by gaand** [comment]
Question 1: seems unrelated to this material so I agree it should be removed.

Question 5: I think you're right and the objectives should be updated.

@ga-wdi-boston/core Other people's thoughts?

**Comment by jrhorn424** [comment]
I agree. Question 1 should be moved to the jquery-ajax series of diagnostics.
